apiversion: apps/v1
kind: DaemonSet
metadata:
   name: example-1
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
     matchLabels:
         app: DaemonSet
  template:
     metadata:
        labels:
           app: DaemonSet
     spec:
       containers:
         - name: nginx
           image: nginx:latest
           ports:
             - containerPort: 80
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: example-4
spec:
  minReadySeconds: 3
  selector:
     matchLabels:
         app: DaemonSet
  template:
     metadata:
        labels:
           app: DaemonSet
     spec:
       containers:
         - name: web
           image: alpine:latest
           command:
              - sleep
              - "3600s"
       