apiVersion: apps/v1
kind: Deployment
metadata:
   name: shop
spec:
  minReadySeconds: 3
  replicas: 2
  revisionHistoryLimit: 10
  selector: 
     matchLabels:
        app: shop
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%
  template:
    metadata:
      labels:
         app: shop
    spec:
      containers:
        - name: shop
          image: nharshitha29/maison:v1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: shop-service
spec:
  type: ClusterIP
  selector:
      app: shop
  ports:
    - name: network
      port: 80
      protocol: TCP
      targetPort: 80