---
apiVersion: v1
kind: Pod
metadata:
   name: example-1
   labels:
      purpose: learning
      env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
   name: example-2
   labels:
      purpose: learning
      env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
   name: example-3
   labels:
      purpose: learning
      env: dev
spec:
  initContainers:
    - name: alpine
      image: alpine:latest
      command:
        - sleep
        - "5s"
    - name: alpine-1
      image: alpine:latest
      command:
        - sleep
        - "8s"
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort:80
---
apiVersion: v1
kind: Pod
metadata:
   name: example-1
   labels:
      purpose: learning
      env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
         requests:
             memory: "64Mi"
             cpu: "250m"
         limits:
             memory: "128Mi"
             cpu: "500m"
