- name: install tomcat 10 on ubuntu 24
  hosts: all
  become: true
  tasks:
    - name: fail if it is not ubuntu
      ansible.builtin.fail:
         msg: playbook runs on only ubuntu
      when: ansible_facts["distribution"] != "Ubuntu" 
    - name: install openjdk 17
      ansible.builtin.apt:
         name: "{{ java_package_name }}"
         state: present
         update_cache: yes
    - name: create tomcat group
      ansible.builtin.group:
         name: "{{ tomcat_user }}"
         state: present
    - name: create tomcat user
      ansible.builtin.user:
         user: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         create_home: yes
         shell: "{{ tomcat_shell }}"
         home: "{{ tomcat_home }}"
    - name: check if /opt/tomcat/bin exists or not
      ansible.builtin.stat:
         path: /opt/tomcat/bin
         register: tomcat_bin
    - name: install tomcat and extract files
      ansible.builtin.unarchive:
         src: "{{ tomcat_download_url }}"
         dest: "{{ tomcat_home }}"
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         remote_src: yes
         extra_opts:
              --strip-components=1
      when: tomcat_bin.stat.exists == false 
    - name: copy the tomcat user 
      ansible.builtin.template:
         src: templates/tomcat-users.xml.j2
         dest: "{{ tomcat_home }}/conf/tomcat-users.xml"
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         mode: '0600'
      notify:
         - enable and restart tomcat service
    - name: copy the context manager file
      ansible.builtin.template:
         src: templates/context.xml.j2
         dest: "{{ tomcat_home }}/webapps/manager/META-INF/context.xml"
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         mode: '0600'
      notify:
         - enable and restart tomcat service
    - name: copy the context host manager file
      ansible.builtin.template:
         src: templates/context.xml.j2
         dest: "{{ tomcat_home }}/webapps/host-manager/META-INF/context.xml"
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         mode: '0600'
      notify:
         - enable and restart tomcat service
    - name: copy the tomcat service file
      ansible.builtin.template:
         src: templates/tomcat-service.j2
         dest: /etc/systemd/system/tomcat.service
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
      notify:
         - enable and restart tomcat service
    - name:  start tomcat
      ansible.builtin.systemd:
         name: tomcat
         state: started
         enabled: true 
  handlers:
      - name: enable and restart tomcat service
        ansible.builtin.systemd:
          name: tomcat
          state: restarted
          daemon_reload: true
          enabled: true  
    