- name: install tomcat 10 on ubuntu 24
  hosts: appserver
  become: yes
  tasks:
    - name: fail if it is not ubuntu
      ansible.builtin.fail:
         msg: playbook runs on only ubuntu
      when: ansible_facts["distribution"] != "Ubuntu" 
    - name: install openjdk 17
      ansible.builtin.apt:
         name: "{{ java_package_name }}"
         state: present
         update_cache: yes
    - name: create tomcat group
      ansible.builtin.group:
         name: "{{ tomcat_user }}"
         state: present
    - name: create tomcat user
      ansible.builtin.user:
         user: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         create_home: yes
         shell: "{{ tomcat_shell }}"
         home: "{{ tomcat_home }}"
    - name: install tomcat and extract files
      ansible.builtin.unarchive:
         src: "{{ tomcat_download_url }}"
         dest: "{{ tomcat_home }}"
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         remote_src: yes
         extra_opts:
              --strip-components=1
    - name: copy the tomcat user 
      ansible.builtin.copy:
         src: files\tomcat-users.xml
         dest: "{{ tomcat_home }}"/conf/tomcat-users.xml
         owner: "{{ tomcat_user }}"
         group: "{{ tomcat_group }}"
         mode: '0600'