---
{{- with .Values.apps.deployment }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: {{ .container.image }}:{{ .container.tag }}
          ports: {{ .container.ports | toYaml | nindent 12 }}
          env:
{{- range .container.env }}
            - name: {{ .name }}
              value: {{ .value }}
{{- end }}
          resources: {{ .container.resources | toYaml | nindent 12 }}
          startupProbe: 
            httpGet: {{ .container.startupProbe.httpGet | toYaml | nindent 14 }}
            failureThreshold: {{ .container.startupProbe.failureThreshold }}
            periodSeconds: {{ .container.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet: {{ .container.readinessProbe.httpGet | toYaml | nindent 14 }}
            failureThreshold: {{ .container.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .container.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .container.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet: {{ .container.livenessProbe.httpGet | toYaml | nindent 14 }} 
            failureThreshold:  {{ .container.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .container.livenessProbe.initialDelaySeconds }}
            periodSeconds:  {{ .container.livenessProbe.periodSeconds }}
{{- end }}
---
{{- with .Values.services.makeline }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type }}
  ports: {{ .ports | toYaml | nindent 4 }}
  selector: {{ .selector | toYaml | nindent 4 }}
{{- end }}


