---
apiVersion: v1
data:
  rabbitmq_enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_amqp1_0].
kind: ConfigMap
metadata:
  name: rabbitmq-enabled-plugins
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
data:
  RABBITMQ_DEFAULT_USER: dXNlcm5hbWU=
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
---
{{- with .Values.apps.rabbitmq }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  serviceName: {{ .serviceName }}
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: rabbitmq
          image: {{ .container.image }}:{{ .container.tag }}
          ports: {{ .container.ports | toYaml | nindent 12 }}
          envFrom:
            - secretRef:
                name: rabbitmq-secrets
          resources: {{ .container.resources | toYaml | nindent 12 }}
          startupProbe: {{ .container.startupProbe | toYaml | nindent 12 }}
          readinessProbe: {{ .container.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .container.livenessProbe | toYaml | nindent 12 }}
          volumeMounts:
            - name: rabbitmq-enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
      volumes:
        - name: rabbitmq-enabled-plugins
          configMap:
            name: rabbitmq-enabled-plugins
            items:
              - key: rabbitmq_enabled_plugins
                path: enabled_plugins
{{- end }}
---
{{- with .Values.services.rabbitmq }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector: {{ .selector | toYaml | nindent 4}}
  ports: {{ .ports | toYaml | nindent 4 }}
  type: {{ .type }}
{{- end }}


