---
apiVersion: v1
data:
  rabbitmq_enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_amqp1_0].
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  RABBITMQ_DEFAULT_USER: dXNlcm5hbWU=
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbit.name }}
spec:
  serviceName: {{ .Values.rabbit.serviceName }}
  replicas: {{ .Values.rabbit.replicas }}
  selector:
    matchLabels: {{ .Values.rabbit.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .Values.rabbit.labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ .Values.container1.name }}
          image: mcr.microsoft.com/azurelinux/base/rabbitmq-server:{{ .Values.container1.tag }}
          ports: {{ .Values.container1.ports | toYaml | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          resources: {{ .Values.container1.resources | toYaml | nindent 12 }}
          startupProbe: {{ .Values.container1.startupProbe | toYaml | nindent 12 }}
          readinessProbe: {{ .Values.container1.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .Values.container1.livenessProbe | toYaml | nindent 12 }}
          volumeMounts:
              - name: rabbitmq-enabled-plugins
                mountPath: /etc/rabbitmq/enabled_plugins
                subPath: enabled_plugins
      volumes:
        - name: {{ .Values.configmap.name }}
          configMap:
            name: {{ .Values.configmap.name }}
            items:
              - key: rabbitmq_enabled_plugins
                path: {{ .Values.path }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbit.name }}
spec:
  selector: {{ .Values.rabbit.labels | toYaml | nindent 6 }}
  ports: {{ .Values.ports | toYaml | nindent 4}}
  type: {{.Values.type1 }}