---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.storeadmin.name }}
spec:
  replicas: {{ .Values.storeadmin.replicas }}
  selector:
    matchLabels: 
       app: {{ .Values.storeadmin.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.storeadmin.name }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: {{ .Values.storeadmin.name }}
          image: ghcr.io/azure-samples/aks-store-demo/store-admin:{{ .Values.storeadmin.tag }}
          ports: {{ .Values.storeadmin.ports | toYaml | nindent 12 }}
          resources: {{ .Values.storeadmin.resources | toYaml | nindent 12 }}
          startupProbe:
            httpGet: {{ .Values.storeadmin.startupProbe.httpGet | toYaml | nindent 14 }}
            failureThreshold: {{ .Values.storeadmin.startupProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.storeadmin.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.storeadmin.startupProbe.periodSeconds }}
          readinessProbe:
            httpGet: {{ .Values.storeadmin.startupProbe.httpGet | toYaml | nindent 14 }}
            failureThreshold: {{ .Values.storeadmin.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.storeadmin.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.storeadmin.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet: {{ .Values.storeadmin.startupProbe.httpGet | toYaml | nindent 14 }}
            failureThreshold: {{ .Values.storeadmin.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.storeadmin.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.storeadmin.livenessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeadmin.name }}
spec:
  ports: {{ .Values.storeadmin.spec.ports | toYaml | nindent 4 }}
  selector:
    app: {{ .Values.storeadmin.name }}
  type: {{ .Values.storeadmin.spec.type }}
