---
{{- with .Values.apps.virtualcustomer }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: virtual-customer
          image: {{ .container.image }}:{{ .container.tag }}
          env:
            - name: ORDER_SERVICE_URL
              value: http://order-service:3000/
            - name: ORDERS_PER_HOUR
              value: "100"
          resources: {{ .container.resources | toYaml | nindent 12 }}
          readinessProbe: {{ .container.readinessProbe | toYaml | nindent 14 }}
          livenessProbe: {{ .container.livenessProbe | toYaml | nindent 14 }} 
{{- end }}
---
{{- with .Values.apps.virtualworker }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: virtual-worker
          image: {{ .container.image }}:{{ .container.tag }}
          env:
            - name: MAKELINE_SERVICE_URL
              value: http://makeline-service:3001
            - name: ORDERS_PER_HOUR
              value: "100"
          resources: {{ .container.resources | toYaml | nindent 12 }}
          readinessProbe: {{ .container.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .container.livenessProbe | toYaml | nindent 12 }}
{{- end }}


